spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
    username: jeongdo
    password: jeongdo1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        foramt_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    open-in-view: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace